import 'package:flutter_test/flutter_test.dart';
import 'package:mobile_app/shared/entities/value_objects.dart';

void main() {
  // Regression: `GeoPoint.fromJson` was generated by json_serializable and
  // read `lat`/`lng` only, but Mongo hands back GeoJSON. Every generated
  // caller — `Order.fromJson`, `AuthUser.fromJson` — therefore threw a
  // null-cast on real data, and it kept being patched per-mapper, so each
  // new call site rediscovered the same crash.
  group('GeoPoint.fromJson reads every shape the platform emits', () {
    test('GeoJSON, with longitude first', () {
      // The trap: [lng, lat], not [lat, lng]. Riyadh is 24.7°N 46.7°E, so
      // reading these the wrong way round puts the point in Somalia without
      // failing.
      final point = GeoPoint.fromJson({
        'type': 'Point',
        'coordinates': [46.6753, 24.7136],
      });

      expect(point.lat, closeTo(24.7136, 1e-9));
      expect(point.lng, closeTo(46.6753, 1e-9));
    });

    test("the app's own lat/lng shape", () {
      final point = GeoPoint.fromJson({'lat': 24.7136, 'lng': 46.6753});
      expect(point.lat, closeTo(24.7136, 1e-9));
      expect(point.lng, closeTo(46.6753, 1e-9));
    });

    test('the REST DTO latitude/longitude spelling', () {
      final point = GeoPoint.fromJson({
        'latitude': 24.7136,
        'longitude': 46.6753,
      });
      expect(point.lat, closeTo(24.7136, 1e-9));
      expect(point.lng, closeTo(46.6753, 1e-9));
    });

    test('integer coordinates, which JSON gives for whole numbers', () {
      final point = GeoPoint.fromJson({
        'type': 'Point',
        'coordinates': [46, 24],
      });
      expect(point.lat, 24.0);
      expect(point.lng, 46.0);
    });

    test('throws on a shape it cannot read, rather than defaulting to 0,0', () {
      // (0, 0) is the Gulf of Guinea — a silent default would put every
      // client's station there and look like a map bug, not a parse bug.
      expect(
        () => GeoPoint.fromJson({'x': 1, 'y': 2}),
        throwsA(isA<FormatException>()),
      );
      expect(
        () => GeoPoint.fromJson({'type': 'Point', 'coordinates': <Object>[]}),
        throwsA(isA<FormatException>()),
      );
    });
  });
}
